repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.1.0"
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
        language_version: python3.8
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.1.7"
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$|\.bat$
    -   id: forbid-tabs
        exclude: Makefile|\.bat$
-   repo: https://github.com/psf/black
    rev: "19.10b0"
    hooks:
        - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: "4.3.21"
    hooks:
    -   id: isort
        additional_dependencies: [toml]
- repo: https://gitlab.com/PyCQA/flake8
  rev: "3.8.3"
  hooks:
  - id: flake8
- repo: https://github.com/PyCQA/bandit
  rev: "1.6.2"
  hooks:
  - id: bandit
    exclude: _tests\.py$
