name: Tests
on: [push]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: docker://thekevjames/nox
      with:
        entrypoint: nox
